/*
Klarna Payments API V1

The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).

**Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.

Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * Customer’s Title. Allowed values per country: UK - \"Mr\", \"Ms\" DE - \"Herr\", \"Frau\" AT: \"Herr, \"Frau\" CH: de-CH: \"Herr, \"Frau\" it-CH: \"Sig.\", \"Sig.ra\" fr-CH: \"M\", \"Mme\"  BE: \"Dhr.\", \"Mevr.\" NL: \"Dhr.\", \"Mevr.\"
     * @type {string}
     * @memberof Address
     */
    'title'?: string;
    /**
     * ‘Attn.’ (if applicable). Only applicable for B2B customers.
     * @type {string}
     * @memberof Address
     */
    'attention'?: string;
    /**
     * Customer’s city.
     * @type {string}
     * @memberof Address
     */
    'city'?: string;
    /**
     * Customer’s country. This value overrides the purchase country if they are different. Should follow the standard of ISO 3166 alpha-2. E.g. GB, US, DE, SE.
     * @type {string}
     * @memberof Address
     */
    'country'?: string;
    /**
     * Customer’s email address.
     * @type {string}
     * @memberof Address
     */
    'email'?: string;
    /**
     * Customers family name in UTF-8 encoding. Cannot be only numbers, must be more than 1 character. Allowed special characters: -\'’. More information can be found [in this link](https://docs.klarna.com/klarna-payments/in-depth-knowledge/customer-data-requirements/#details-needed-per-market)
     * @type {string}
     * @memberof Address
     */
    'family_name'?: string;
    /**
     * Customers given name in UTF-8 encoding. Cannot be only numbers, must be more than 1 character. Allowed special characters: -\'’. More information can be found [in this link](https://docs.klarna.com/klarna-payments/in-depth-knowledge/customer-data-requirements/#details-needed-per-market)
     * @type {string}
     * @memberof Address
     */
    'given_name'?: string;
    /**
     * Organization name (if applicable). Only applicable for B2B customers.
     * @type {string}
     * @memberof Address
     */
    'organization_name'?: string;
    /**
     * Phone number. Preferably a mobile phone number.
     * @type {string}
     * @memberof Address
     */
    'phone'?: string;
    /**
     * Customer’s postal code. Validation according to Universal Postal Union addressing systems. E.g. 12345, W1G OPW.
     * @type {string}
     * @memberof Address
     */
    'postal_code'?: string;
    /**
     * Customer’s region or state - Mandatory for US and AU market. Validations according to ISO 3166-2 format, e.g. OH, NJ, etc.
     * @type {string}
     * @memberof Address
     */
    'region'?: string;
    /**
     * Customer’s street address. Regional formatting is required, as follows: UK/US/FR: 33 Cavendish Square Rest of EU: De Ruijterkade 7
     * @type {string}
     * @memberof Address
     */
    'street_address'?: string;
    /**
     * Customer’s street address. Second Line. 
     * @type {string}
     * @memberof Address
     */
    'street_address2'?: string;
}

