/*
Klarna Payments API V1

The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).

**Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.

Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AssetUrls
 */
export interface AssetUrls {
    /**
     * URL of the descriptive asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
     * @type {string}
     * @memberof AssetUrls
     */
    'descriptive'?: string;
    /**
     * URL of the standard asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
     * @type {string}
     * @memberof AssetUrls
     */
    'standard'?: string;
}

