/*
Klarna Payments API V1

The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).

**Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.

Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { CustomerReadCreateToken } from './customer-read-create-token';

/**
 * 
 * @export
 * @interface CustomerTokenCreationResponse
 */
export interface CustomerTokenCreationResponse {
    /**
     * 
     * @type {Address}
     * @memberof CustomerTokenCreationResponse
     */
    'billing_address'?: Address;
    /**
     * 
     * @type {CustomerReadCreateToken}
     * @memberof CustomerTokenCreationResponse
     */
    'customer'?: CustomerReadCreateToken;
    /**
     * Used to connect customers with payment method when it is present.
     * @type {string}
     * @memberof CustomerTokenCreationResponse
     */
    'payment_method_reference'?: string;
    /**
     * URL to redirect the customer to after placing the order. This is a Klarna URL where Klarna will place a cookie in the customer’s browser (if redirected) and redirect the customer back to the confirmation URL provided by the merchant. This is not a mandatory step but a recommended one to improve the returning customer’s experience.
     * @type {string}
     * @memberof CustomerTokenCreationResponse
     */
    'redirect_url'?: string;
    /**
     * Generated customer token. This token will be used to create a new order for the subscription using the Create a New order using token API.
     * @type {string}
     * @memberof CustomerTokenCreationResponse
     */
    'token_id': string;
}

