/*
Klarna Payments API V1

The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).

**Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.

Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Customer } from './customer';

/**
 * 
 * @export
 * @interface CustomerTokenCreationRequest
 */
export interface CustomerTokenCreationRequest {
    /**
     * Description of the purpose of the token.
     * @type {string}
     * @memberof CustomerTokenCreationRequest
     */
    'description': string;
    /**
     * 
     * @type {Address}
     * @memberof CustomerTokenCreationRequest
     */
    'billing_address'?: Address;
    /**
     * 
     * @type {Customer}
     * @memberof CustomerTokenCreationRequest
     */
    'customer'?: Customer;
    /**
     * Intended use for the token.
     * @type {string}
     * @memberof CustomerTokenCreationRequest
     */
    'intended_use': CustomerTokenCreationRequestIntendedUseEnum;
    /**
     * RFC 1766 customer\'s locale.
     * @type {string}
     * @memberof CustomerTokenCreationRequest
     */
    'locale': string;
    /**
     * ISO 3166 alpha-2 purchase country.
     * @type {string}
     * @memberof CustomerTokenCreationRequest
     */
    'purchase_country': string;
    /**
     * ISO 4217 purchase currency.
     * @type {string}
     * @memberof CustomerTokenCreationRequest
     */
    'purchase_currency': string;
}

type CustomerTokenCreationRequestIntendedUseEnum = 'SUBSCRIPTION'


